server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/endTerm
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none

rsa:
  private-key: classpath:static/private.pem
  public-key: classpath:static/public.pem
