CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(320),
    password   TEXT,
    primary key(id)
);


create table if not exists posts
(
    author_id        BIGINT,
    date_of_creation timestamp(6) with time zone,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text             varchar(255),
    title            varchar(255),
    primary key(id),
    CONSTRAINT post_user FOREIGN KEY (author_id) REFERENCES users(id)
    );
